// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLGee4BIrdTcF_C1uqSxyESWgHWjJy3W0',
    appId: '1:686545923071:web:95ff8067f25ae5ff8715ca',
    messagingSenderId: '686545923071',
    projectId: 'fir-c987f',
    authDomain: 'fir-c987f.firebaseapp.com',
    storageBucket: 'fir-c987f.appspot.com',
    measurementId: 'G-8RCBZ1X5J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qt7ygu5Qb6OpZSo3veHktercKTjeY_4',
    appId: '1:686545923071:android:b8d065fbd2d921f18715ca',
    messagingSenderId: '686545923071',
    projectId: 'fir-c987f',
    storageBucket: 'fir-c987f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1DwICZ3uVXBQ0kSLeZrn01G3ns32QR4',
    appId: '1:686545923071:ios:f238198c46b481728715ca',
    messagingSenderId: '686545923071',
    projectId: 'fir-c987f',
    storageBucket: 'fir-c987f.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1DwICZ3uVXBQ0kSLeZrn01G3ns32QR4',
    appId: '1:686545923071:ios:73bce8b879354d6d8715ca',
    messagingSenderId: '686545923071',
    projectId: 'fir-c987f',
    storageBucket: 'fir-c987f.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
